<a href="https://colab.research.google.com/github/UrielErick762/Funcoes_Pandas_Notebook/blob/main/Pandas_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importação da biblioteca

Primeiro, importamos a biblioteca Pandas e por padrão, a instanciamos com 'pd'.

Em notebooks Jupyter, como o Google Colab, não há a necessidade de instalar localmente.

Para que funcione em IDEs localmente, a instalação deve ser realizada via terminal.

In [538]:
import pandas as pd

pd.__version__

'2.2.2'

## Importação de dados

A classe `DataFrame` serve para que possamos retornar uma tabela no Python.
Abaixo temos o seguinte:

* A variável `dados` armazena um dicionário (tudo que está dentro de `{}`).
* O dicionário é composto por várias chaves (`nome`, `idade`, `altura`, `peso`, `cidade`).
* Cada chave possui uma lista de valores (os dados que correspondem a cada chave) relacionada a uma coluna do DataFrame.

Com a variável `dados` elaborada, instanciamos os valores através da variável `df`, que, por sua vez, recebe o construtor `pd.DataFrame()`.

In [539]:
dados = {
    'nome': ['Lucas', 'Joseph', 'Carl', 'Ana', None, 'Erick', 'Marcus'],
    'idade': [23, 35, None, 23, 40, '45', '22'],
    'altura': [1.65, 1.80, 1.75, 1.65, None, 1.70, 1.85],
    'peso': [55, 80, 77, 55, 90, None, 93],
    'estado': ['SP', 'MG', 'SP', 'SC', 'PR', 'MS', 'GO']
}

df = pd.DataFrame(dados)

df

     nome idade  altura  peso estado
0   Lucas    23    1.65  55.0     SP
1  Joseph    35    1.80  80.0     MG
2    Carl  None    1.75  77.0     SP
3     Ana    23    1.65  55.0     SC
4    None    40     NaN  90.0     PR
5   Erick    45    1.70   NaN     MS
6  Marcus    22    1.85  93.0     GO

Também podemos retornar uma coluna em específico, ao invés de um DataFrame completo, usando o tipo `Series`.

* Instanciamos uma nova variável.
* Atribuímos o valor de `df['nome_da_coluna']` (onde `nome_da_coluna` é o nome da coluna que queremos retornar).

In [540]:
nome_series = df['nome']

nome_series

0     Lucas
1    Joseph
2      Carl
3       Ana
4      None
5     Erick
6    Marcus
Name: nome, dtype: object

Porém, quando trabalhamos com dados, precisamos importá-los de algum lugar, seja uma planilha XLSX, CSV ou algum outro tipo de arquivo.

Para essa importação de dados, precisamos usar a família de métodos `read_`.

In [541]:
# df = pd.read_csv('nome_do_arquivo.csv')
# df = pd.read_excel('nome_do_arquivo.xlsx', sheet_name = "nome da aba do arquivo")

## Análise de dados

Para casos em que o DataFrame tem um grande volume de dados, podemos observar somente os primeiros 5 registros utilizando o método `.head()`.

In [542]:
df.head()

     nome idade  altura  peso estado
0   Lucas    23    1.65  55.0     SP
1  Joseph    35    1.80  80.0     MG
2    Carl  None    1.75  77.0     SP
3     Ana    23    1.65  55.0     SC
4    None    40     NaN  90.0     PR

Ou pode-se optar por usar o método `.tail()` para visualizar os últimos registros do DataFrame.

In [543]:
df.tail()

     nome idade  altura  peso estado
2    Carl  None    1.75  77.0     SP
3     Ana    23    1.65  55.0     SC
4    None    40     NaN  90.0     PR
5   Erick    45    1.70   NaN     MS
6  Marcus    22    1.85  93.0     GO

Podemos validar os dados usando uma comparação booleana.

Se adicionarmos uma condição para comparação e referenciarmos a coluna, podemos obter um resultado booleano.

In [544]:
df['altura'] >= 1.70

0    False
1     True
2     True
3    False
4    False
5     True
6     True
Name: altura, dtype: bool

Com essa comparação booleana, podemos aplicar filtros chamando a variável `df` e passando a condição para que nos retorne apenas o que desejamos.

In [545]:
df[df['altura'] >= 1.70]

     nome idade  altura  peso estado
1  Joseph    35    1.80  80.0     MG
2    Carl  None    1.75  77.0     SP
5   Erick    45    1.70   NaN     MS
6  Marcus    22    1.85  93.0     GO

Voltando ao DataFrame completo, podemos observar que valores ausentes recebem a sigla NaN (Not a Number).

Essas ausências ou faltas de valores são uma constante de ponto flutuante estabelecida pelo padrão IEEE (Instituto de Engenheiros Eletricistas e Eletrônicos).

Para uma análise de dados utilizando Pandas, não podemos ter campos com ausência de valores.

Nesses casos, realizamos os próximos passos de análise e limpeza de dados para que não resulte em nenhum erro em nossa análise.

Começamos com a análise dos dados usando o método `.info()`.

O método `.info()` irá nos mostrar:
* Valores não nulos
* Tipos de dados
* Tamanho da memória utilizada

In [546]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    6 non-null      object
 1   idade   6 non-null      object
 2   altura  6 non-null      float64
 3   peso    6 non-null      float64
 4   estado  7 non-null      object
dtypes: float64(2), object(3)
memory usage: 412.0+ bytes

O método `.describe()` gera um resumo estatístico rápido das colunas numéricas (e opcionalmente categóricas) de um DataFrame, facilitando a análise exploratória de dados.

In [547]:
df.describe()

         altura       peso
count  6.000000   6.000000
mean   1.733333  75.000000
std    0.081650  16.601205
min    1.650000  55.000000
25%    1.662500  60.500000
50%    1.725000  78.500000
75%    1.787500  87.500000
max    1.850000  93.000000

### Ordenação de dados

Podemos ordenar nossos resultados usando o método `.sort_values()`.

In [548]:
df.sort_values(by='altura')

     nome idade  altura  peso estado
0   Lucas    23    1.65  55.0     SP
3     Ana    23    1.65  55.0     SC
5   Erick    45    1.70   NaN     MS
2    Carl  None    1.75  77.0     SP
1  Joseph    35    1.80  80.0     MG
6  Marcus    22    1.85  93.0     GO
4    None    40     NaN  90.0     PR

Para ordenarmos do maior para o menor, usamos o parâmetro `ascending=False`.

In [549]:
df.sort_values(by='altura', ascending=False)

     nome idade  altura  peso estado
6  Marcus    22    1.85  93.0     GO
1  Joseph    35    1.80  80.0     MG
2    Carl  None    1.75  77.0     SP
5   Erick    45    1.70   NaN     MS
0   Lucas    23    1.65  55.0     SP
3     Ana    23    1.65  55.0     SC
4    None    40     NaN  90.0     PR

## Tratamento de dados

Se observar a coluna `idade`, ela contém valores não numéricos (tipo `object`).

Se tivermos que fazer alguma operação matemática, precisamos converter esses dados para tipos numéricos (`int` ou `float`).

In [550]:
df['idade'] = pd.to_numeric(df['idade'], errors='coerce')
df

     nome  idade  altura  peso estado
0   Lucas   23.0    1.65  55.0     SP
1  Joseph   35.0    1.80  80.0     MG
2    Carl    NaN    1.75  77.0     SP
3     Ana   23.0    1.65  55.0     SC
4    None   40.0     NaN  90.0     PR
5   Erick   45.0    1.70   NaN     MS
6  Marcus   22.0    1.85  93.0     GO

### Adicionando colunas.

Podemos adicionar novas colunas informando, primeiramente, o nome da nova coluna e qual condição ou cálculo irá retornar os dados.

In [551]:
df['idade_proxima_decada'] = df['idade'] + 10
df

     nome  idade  altura  peso estado  idade_proxima_decada
0   Lucas   23.0    1.65  55.0     SP                  33.0
1  Joseph   35.0    1.80  80.0     MG                  45.0
2    Carl    NaN    1.75  77.0     SP                   NaN
3     Ana   23.0    1.65  55.0     SC                  33.0
4    None   40.0     NaN  90.0     PR                  50.0
5   Erick   45.0    1.70   NaN     MS                  55.0
6  Marcus   22.0    1.85  93.0     GO                  32.0

### Remover colunas

Para indicarmos que estamos removendo uma coluna, devemos especificar o nome da coluna juntamente com o parâmetro `axis=1`.

In [552]:
df = df.drop('idade_proxima_decada', axis=1)

df

     nome  idade  altura  peso estado
0   Lucas   23.0    1.65  55.0     SP
1  Joseph   35.0    1.80  80.0     MG
2    Carl    NaN    1.75  77.0     SP
3     Ana   23.0    1.65  55.0     SC
4    None   40.0     NaN  90.0     PR
5   Erick   45.0    1.70   NaN     MS
6  Marcus   22.0    1.85  93.0     GO

### Limpeza de dados

Quando trabalhamos com dados, não podemos ter valores nulos, uma vez que esses valores faltantes atrapalhariam nossa análise.

Pensando nisso, podemos usar o método `.dropna()` para a remoção desses dados faltantes.

Obtemos como resultado apenas os registros onde todos os campos estão preenchidos.

In [553]:
df.dropna()

     nome  idade  altura  peso estado
0   Lucas   23.0    1.65  55.0     SP
1  Joseph   35.0    1.80  80.0     MG
3     Ana   23.0    1.65  55.0     SC
6  Marcus   22.0    1.85  93.0     GO

### Limpeza focada em apenas uma coluna.

Para uma limpeza focada em apenas uma coluna, usamos o parâmetro `subset`.

In [554]:
df.dropna(subset= 'idade')

     nome  idade  altura  peso estado
0   Lucas   23.0    1.65  55.0     SP
1  Joseph   35.0    1.80  80.0     MG
3     Ana   23.0    1.65  55.0     SC
4    None   40.0     NaN  90.0     PR
5   Erick   45.0    1.70   NaN     MS
6  Marcus   22.0    1.85  93.0     GO

### Preenchimento de campos nulos.

Quando precisamos preencher campos nulos, podemos usar o método `.fillna()`.

In [555]:
df = df.fillna(0)

df

     nome  idade  altura  peso estado
0   Lucas   23.0    1.65  55.0     SP
1  Joseph   35.0    1.80  80.0     MG
2    Carl    0.0    1.75  77.0     SP
3     Ana   23.0    1.65  55.0     SC
4       0   40.0    0.00  90.0     PR
5   Erick   45.0    1.70   0.0     MS
6  Marcus   22.0    1.85  93.0     GO

### Convertendo para tipos inteiros

Para converter um valor para inteiro, usamos o método `.astype(int)`.

In [558]:
df['idade'] = df['idade'].astype(int)
df

     nome  idade  altura  peso estado
0   Lucas     23    1.65  55.0     SP
1  Joseph     35    1.80  80.0     MG
2    Carl      0    1.75  77.0     SP
3     Ana     23    1.65  55.0     SC
4       0     40    0.00  90.0     PR
5   Erick     45    1.70   0.0     MS
6  Marcus     22    1.85  93.0     GO

### Contagem de ocorrências.

Para a contagem de ocorrências, usamos o método `.value_counts()`.

In [557]:
df['estado'].value_counts()

estado
SP    2
MG    1
SC    1
PR    1
MS    1
GO    1
Name: count, dtype: int64

**Referências:**



*   https://pandas.pydata.org/docs/user_guide/index.html#user-guide
*   https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html
*   https://www.youtube.com/watch?v=1JpYOqvDJNU&t=1s